spring.application.name=talentbridge-ats

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/talentbridge_ats?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kasundi123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:change-this-to-a-long-random-string-at-least-32-chars}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

server.port=${PORT:8080}